### ISSUE TITLE
Mekanism pipes dont push/pull into drawers, only into controllers

### ISSUE THREAD

**Issue by WintersPride** [davqvist/Q-Tech#18]
title, makes automation/storage annoying

**Comment by davqvist** [comment]
I tested this 2 days ago, sometimes it doesn't work with controllers either. But adding empty drawers sometimes work. It seems that either the pipes read the inventory space wrong or vice versa. Use XNet or RS in the mean time.

**Comment by davqvist** [comment]
Or use Mekanism Bins instead. I looked at the Storage Drawers github and it is reported there already, seemingly an issue on their end.

**Comment by davqvist** [comment]
Storage Drawers got removed
