### ISSUE TITLE
infinite blaze rods.

### ISSUE THREAD

**Issue by WintersPride** [davqvist/Q-Tech#19]
You can use silent's crusher to crush 1 blaze rod into 4 powder and use silent's compressor to turn 2 dust into 1 rod.

seems pretty powerful but maybe a temporary fix to not having a mob grinder for blazes.

**Comment by davqvist** [comment]
I will just disable the Compressor recipe or make 4-5 Powder.

**Comment by davqvist** [comment]
It is fixed in the mod in an update and will be fixed in upcoming beta.
