### ISSUE TITLE
just crashes

### ISSUE THREAD

**Issue by wait-a-second** [davqvist/Q-Tech#32]
when I launch the game it just crashes and says "error code: 0"
![crash](https://user-images.githubusercontent.com/70474821/91659968-c90c8600-eadb-11ea-8661-abcf3d148ab3.PNG)

**Comment by davqvist** [comment]
I assume you are using Twitch Launcher, that is the bug that I mention in the description of the pack. It is an issue that is affecting some people and I can't do anything about it, Please use another launcher like GDLauncher or MultiMC which is probably the easiest fix for this.
