### ISSUE TITLE
Crash when pressing on "Video Settings"

### ISSUE THREAD

**Issue by Chellyyyyy** [davqvist/Q-Tech#33]
I'm using MultiMC and have only added Optifine. Whenever I press on "Video Settings" the game crashes, help would be appreciated. 
[crash-2020-08-30_16.22.32-client.txt](https://github.com/davqvist/Q-Tech/files/5147411/crash-2020-08-30_16.22.32-client.txt)

**Comment by davqvist** [comment]
Remove Optifine it is not needed as performance increasing mods are already in the pack. 
If you want Optifine for shaders try updating TIpTheScales manually.
