### ISSUE TITLE
Xnet network cable only accepts vanilla string

### ISSUE THREAD

**Issue by NeoPangea** [davqvist/Q-Tech#37]
When I first spawned I found flax (Silentgear) plants and grabbed some seeds. I have been playing for a while now having my small flax farm providing all my string needs but I recently got to using an xnet controller and could not make the network cable since that only accepts the vanilla string. I went and hunted a few spiders but it would be great if the recipe could accept both types of string. I saw a couple of people playing various versions of the pack and they were using the blue power flax for string but for the life of me I cannot figure out where to get those seeds from.

**Comment by davqvist** [comment]
Will be in next update
