### ISSUE TITLE
Silent's steel not working with blueprint

### ISSUE THREAD

**Issue by WintersPride** [davqvist/Q-Tech#6]
Silent's mechanisms steel isn't working with the pickaxe blueprint. 
![image](https://user-images.githubusercontent.com/64622986/80775316-25529f80-8b14-11ea-9c63-d7c141f86178.png)

**Comment by WintersPride** [comment]
to be clear I tried it with 1 stick, 1 iron tool rod, 2 iron tool rods and 2 sticks.

**Comment by davqvist** [comment]
If you look in the Crafting Station you see supported mats like Refined Iron and Compressed Iron but not steel. I wonder if I could add custom materials?

**Comment by davqvist** [comment]
Can't find a way to add custom materials right now, will close for now
