### ISSUE TITLE
Smooth Sandstone and Polished Sandstone recipe issues

### ISSUE THREAD

**Issue by ghost** [davqvist/Q-Tech#9]
Making smooth sandstone or polished sandstone seems to be impossible because both of them require the other, and I wasn't able to find any other way to make either of them, there's the same issue with the red variant

**Comment by davqvist** [comment]
Forgot to add a note in JEI, but you are supposed to use the Stonecutter.

**Comment by davqvist** [comment]
I looked again at it, and you make it in the furnace not in the stonecutter, should show in JEI.
